server:
  port: 8080
  servlet:
    context-path: /api/v1
  tomcat:
    basedir: D:/temp
spring:
  application:
    name: peach-scheduler
peach-scheduler:
  cluster: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,scheduler
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    scheduler:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
