spring:
  profiles:
    include: server,db,log
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,scheduler
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    scheduler:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}